
package org.example;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Impl", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Impl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "make", targetNamespace = "http://example.org/", className = "org.example.Make")
    @ResponseWrapper(localName = "makeResponse", targetNamespace = "http://example.org/", className = "org.example.MakeResponse")
    @Action(input = "http://example.org/Impl/makeRequest", output = "http://example.org/Impl/makeResponse")
    public void make(
        @WebParam(name = "arg0", targetNamespace = "")
        Event arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getId", targetNamespace = "http://example.org/", className = "org.example.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://example.org/", className = "org.example.GetIdResponse")
    @Action(input = "http://example.org/Impl/getIdRequest", output = "http://example.org/Impl/getIdResponse")
    public int getId();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByWeek", targetNamespace = "http://example.org/", className = "org.example.GetByWeek")
    @ResponseWrapper(localName = "getByWeekResponse", targetNamespace = "http://example.org/", className = "org.example.GetByWeekResponse")
    @Action(input = "http://example.org/Impl/getByWeekRequest", output = "http://example.org/Impl/getByWeekResponse")
    public List<Object> getByWeek(
        @WebParam(name = "arg0", targetNamespace = "")
        LocalDate arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.Event
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventByDate", targetNamespace = "http://example.org/", className = "org.example.GetEventByDate")
    @ResponseWrapper(localName = "getEventByDateResponse", targetNamespace = "http://example.org/", className = "org.example.GetEventByDateResponse")
    @Action(input = "http://example.org/Impl/getEventByDateRequest", output = "http://example.org/Impl/getEventByDateResponse")
    public Event getEventByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        LocalDate arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://example.org/", className = "org.example.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://example.org/", className = "org.example.GetInfoResponse")
    @Action(input = "http://example.org/Impl/getInfoRequest", output = "http://example.org/Impl/getInfoResponse")
    public String getInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.Event
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://example.org/", className = "org.example.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://example.org/", className = "org.example.GetByIdResponse")
    @Action(input = "http://example.org/Impl/getByIdRequest", output = "http://example.org/Impl/getByIdResponse")
    public Event getById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://example.org/", className = "org.example.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://example.org/", className = "org.example.GetServerNameResponse")
    @Action(input = "http://example.org/Impl/getServerNameRequest", output = "http://example.org/Impl/getServerNameResponse")
    public String getServerName();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "edit", targetNamespace = "http://example.org/", className = "org.example.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://example.org/", className = "org.example.EditResponse")
    @Action(input = "http://example.org/Impl/editRequest", output = "http://example.org/Impl/editResponse")
    public void edit(
        @WebParam(name = "arg0", targetNamespace = "")
        Event arg0);
}
